<?php
    $validate = $this->validate();
    $message = $validate['msg'];
    $image = $this->getSkinUrl('tmoney/img/success.png');
    $url = Mage::getUrl('/');
?>
<div class="success-page-tigomoney">
    <div class="image"><img src="<?php echo $image ?>" alt="Exito" /></div>
    <div class="page-title category-title">
	<h2><?php echo $this->__('Felicidades') ?></h2>
    </div>
    <section class="message">
        <?php 
            $message_block = $this->getLayout()->createBlock('cms/block')->setBlockId('success_tigomoney')->toHtml();
            if($message_block){
               echo $message_block;
            }else{
                echo '<p>Felicidades la transaccion se ha realizado.</p>';
            }
        ?>
        <p><?php echo $this->__($message) ?></p>
        <div class="content-buttons">
            <a class="button" href="<?php echo $url ?>">Continuar comprando</a>
        </div>
    </section>
</div>
